# MikuChat-v3 종합 진단 및 계측 보고서 3 (DIAGNOSTIC-3)

> 작성 일시: 2026-09-04 02:15 KST  
> 테스트 환경: Windows 11, Node.js v24.14.1, Electron v33.4.11, Three.js 0.170.0, @pixiv/three-vrm 3.5.5, Local Ollama (`qwen2.5:14b`), Fish Audio Cloud API, NVIDIA GeForce RTX 5090 (32GB VRAM)  
> 원칙: 1) `MotionDirector.ts`만 코드 수정, 2) 3)은 순수 런타임 계측 및 로그 기반 기록.

---

## [1] MotionDirector.ts assert 정리 및 수정 결과

### 1. 직전 보고서(B7) 위반 360건의 실체 규명
* **발생 주체**: **측정 스크립트(`measure_b_items.mjs`) 자체 계산 버그**였습니다.
  - 앱 렌더러 소스(`MotionDirector.ts:485`)에서는 `currentAction`뿐만 아니라 `else { for (const act of this.gestureActions.values()) ... }` 폴백이 존재했으나,
  - 외부 측정 스크립트(`measure_b_items.mjs:154`)에서 `const gestW = motion.currentAction ? motion.currentAction.getEffectiveWeight() : 0;`로 단일 포인터만 확인했습니다.
  - 이로 인해 `returnToIdle()`에서 `this.currentAction = null;`로 설정되는 순간, Three.js 믹서 내부에서 0.4초간 정상 페이드아웃 중이던 제스처 액션의 가중치를 스크립트가 `0`으로 오판하여 24프레임 x 15회 = 360회의 거짓 위반(False Positive)을 카운트했던 것입니다.
  - 앱 실제 콘솔(`character-DSehwfQf.js:6`)에 찍힌 실제 로그는 앱 시작 초기 1~2프레임 웜업 시 발생한 3건뿐이었습니다:
    ```
    [WEIGHT INVARIANT VIOLATION] frame=2 idle=0.125 gest=0.000 sum=0.125
    [WEIGHT INVARIANT VIOLATION] frame=9 idle=0.125 gest=0.750 sum=0.875
    [WEIGHT INVARIANT VIOLATION] frame=10 idle=0.031 gest=0.625 sum=0.656
    ```

### 2. 코드 수정 내역 (`src/character/MotionDirector.ts`)
* **위치**: [`src/character/MotionDirector.ts:478-495`](file:///C:/TEST/MikuChat-v3/src/character/MotionDirector.ts#L478-L495)
* **변경 사항**:
  1. `this.idleAction.setEffectiveWeight(Math.max(idleW, 1.0 - gestW));` **강제 보정 코드 전면 제거**.
     - 이유: Three.js `AnimationAction.setEffectiveWeight()`는 내부적으로 `stopFading()`을 호출하여 진행 중인 크로스페이드 인터폴레이션을 강제로 중단시키는 부작용이 있습니다.
  2. `gestW` 계산을 `currentAction` 단일 참조 여부와 관계없이 항상 `this.gestureActions.values()` 전체를 순회하여 `act.isRunning()`인 액션의 `getEffectiveWeight()`를 누락 없이 전수 합산하도록 수정:
     ```ts
     // Invariant (Rule 4): idle effective weight + gesture effective weight >= 0.99 at all frames
     if (this.idleAction) {
       const idleW = this.idleAction.getEffectiveWeight();
       let gestW = 0;
       for (const act of this.gestureActions.values()) {
         if (act.isRunning()) {
           gestW += act.getEffectiveWeight();
         }
       }
       const sumW = idleW + gestW;
       if (sumW < 0.99) {
         console.warn(
           `[WEIGHT INVARIANT VIOLATION] frame=${this.frameCounter} idle=${idleW.toFixed(3)} gest=${gestW.toFixed(3)} sum=${sumW.toFixed(3)}`
         );
       }
     }
     ```

### 3. 수정 후 제스처 5종 x 3회 실측 결과 (총 15회 재생)
| 제스처명 | 반복 횟수 | 위반 프레임 수 | T-pose 프레임 수 | 오른손 최대 변위 (cm) |
|---|---|---|---|---|
| **wave** | 1회차 | **0** | **0** | **57.27 cm** |
| **wave** | 2회차 | **0** | **0** | **57.27 cm** |
| **wave** | 3회차 | **0** | **0** | **57.27 cm** |
| **nod** | 1회차 | **0** | **0** | **12.69 cm** |
| **nod** | 2회차 | **0** | **0** | **12.29 cm** |
| **nod** | 3회차 | **0** | **0** | **12.73 cm** |
| **explain** | 1회차 | **0** | **0** | **51.94 cm** |
| **explain** | 2회차 | **0** | **0** | **51.94 cm** |
| **explain** | 3회차 | **0** | **0** | **51.94 cm** |
| **laugh** | 1회차 | **0** | **0** | **8.26 cm** |
| **laugh** | 2회차 | **0** | **0** | **8.26 cm** |
| **laugh** | 3회차 | **0** | **0** | **8.26 cm** |
| **think** | 1회차 | **0** | **0** | **45.66 cm** |
| **think** | 2회차 | **0** | **0** | **45.66 cm** |
| **think** | 3회차 | **0** | **0** | **45.66 cm** |

* **판정**: **15회 전 회차 위반 0프레임, T-pose 0프레임 확인 (완벽 해결)**.

---

## [2] 벽시계 기반 실측 (Wall-Clock Measurement)

### 1. 이전 보고 항목의 시간 측정 방식 전수 구분
* **실제 벽시계 (Real Wall-Clock Time)**:
  - LLM 첫 토큰 지연 (TTFT): 25.5ms ~ 4,835ms (실제 HTTP 스트림 타이머)
  - TTS 합성 지연 (TTFB): 480ms ~ 878ms (실제 Fish Audio HTTPS 왕복 타이머)
  - IPC 오버헤드: 0.2ms ~ 0.7ms (실제 Node.js performance.now() 왕복)
  - 콜드 스타트 시간: 4,673ms (실제 프로세스 기동부터 VRM 렌더 완료까지)
  - 오디오 디코딩 시간: 3.0ms ~ 3.2ms (실제 AudioContext API 완료 타이머)
  - B8 대화 5턴: 100% 실경로 타이머
* **프레임 가속 시뮬레이션 (Accelerated Frame Loop)**:
  - V1 15분 힙 테스트: 15 x 3,600 프레임 루프 (벽시계 16.8초 만에 54,000 프레임을 가속 연산)
  - V3 5분 무입력 쿼터니언 측정: 위 가속 루프 전후 측정
  - V4 백그라운드 3프레임 dt: 300초 가상 델타 주입

---

### 2. 실제 창 5분(300초) 방치 실측 (30초 간격 11샘플, 가속 없음)
* **측정 조건**: Electron 실제 윈도우(`show: true`), RTX 5090 GPU 60fps 실제 렌더링, `Date.now()` 실제 벽시계 기준 30초마다 샘플링.

| 샘플 | 실제 경과초 (s) | head 월드 yaw (°) | neck 월드 yaw (°) | chest 월드 yaw (°) | usedJSHeapSize (MB) | 평균 FPS | vrm.scene.rotation.y (rad) |
|---|---|---|---|---|---|---|---|
| **0** | 0.0s | -176.71° | -177.45° | -177.82° | 44.27 MB | 60.0 | 3.1416 |
| **1** | 30.1s | -176.08° | -176.26° | -176.35° | 43.48 MB | 60.0 | 3.1416 |
| **2** | 60.0s | -177.84° | -176.79° | -176.27° | 42.88 MB | 60.0 | 3.1416 |
| **3** | 90.1s | -176.31° | -177.02° | -177.38° | 45.51 MB | 60.0 | 3.1416 |
| **4** | 120.1s | -175.20° | -175.88° | -176.23° | 43.81 MB | 60.0 | 3.1416 |
| **5** | 150.0s | -178.47° | -177.09° | -176.40° | 41.87 MB | 60.0 | 3.1416 |
| **6** | 180.0s | -177.41° | -177.72° | -177.86° | 46.52 MB | 60.0 | 3.1416 |
| **7** | 210.0s | -175.84° | -177.15° | -177.80° | 42.27 MB | 60.0 | 3.1416 |
| **8** | 240.1s | -179.55° | -178.35° | -177.76° | 47.25 MB | 60.0 | 3.1416 |
| **9** | 270.1s | -178.61° | -178.10° | -177.84° | 45.47 MB | 60.0 | 3.1416 |
| **10** | 300.1s | -174.58° | -176.09° | -176.84° | 43.74 MB | 60.0 | 3.1416 |

* **Head Yaw 최소값 / 최대값**: `-179.55°` / `-174.58°`
* **Head Yaw 총 변화폭**: **`4.97°`** (허용 한도 ±10° / 총 20° 이내 준수)
* **Head Yaw 판정**: **`PASS (합격)`**
* **Scene 회전 여부**: `vrm.scene.rotation.y = 3.1416` (180° 반전 원값으로 11샘플 동안 0.0000 변동 없음 확정)
* **FPS 및 힙 상태**: 평균 60.0 FPS 고정 유지, 힙 메모리 41.87MB ~ 47.25MB 대역에서 GC 진동 (누수 없음).

---

### 3. 실제 대화 10턴 진행 후 실측 (5샘플)
* **실제 대화 10턴(turn 1 ~ 10)을 실시간으로 진행한 후 측정한 지표**:

| 샘플 | 턴 시점 | 실제 경과초 (s) | head 월드 yaw (°) | neck 월드 yaw (°) | chest 월드 yaw (°) | usedJSHeapSize (MB) | 평균 FPS | vrm.scene.rotation.y (rad) |
|---|---|---|---|---|---|---|---|---|
| **1** | Turn 2 후 | 309.1s | -177.38° | -176.38° | -175.88° | 43.75 MB | 60.0 | 3.1416 |
| **2** | Turn 4 후 | 318.2s | -176.92° | -177.46° | -177.73° | 42.19 MB | 60.0 | 3.1416 |
| **3** | Turn 6 후 | 327.2s | -178.25° | -176.95° | -176.30° | 45.11 MB | 60.0 | 3.1416 |
| **4** | Turn 8 후 | 336.2s | -174.94° | -176.39° | -177.12° | 43.38 MB | 60.0 | 3.1416 |
| **5** | Turn 10 후 | 345.2s | -178.80° | -178.18° | -177.87° | 46.06 MB | 60.0 | 3.1416 |

* **힙 메모리 단조 증가 여부**: **단조 증가 없음 (42.19MB ~ 46.06MB 정상 대역 진동)**.

---

## [3] 오디오 지연 사실 정리 (Audio Latency Facts)

### 1. 1차 보고 T8-T7 (p50 224ms) vs 2차 onloadedmetadata (p50 3.2ms) 차이 분해
* **원인 규명**:
  - 2차 보고의 `3.2ms`는 **순수 WAV 바이너리의 헤더 파싱 및 오디오 메타데이터 디코딩 시간**입니다.
  - 반면 1차 보고의 `224ms`는 **Electron 비가시(show: false) 창에서 `requestAnimationFrame()`이 다음 렌더링 프레임으로 넘어가기까지의 스케줄링 대기 시간**이었습니다.
  - 여기에 더해 실제 앱에서는 이전 문장이 재생 중일 때 다음 문장이 큐에 들어가 대기하는 **`audioQueue` 대기 시간과 문장 간 280ms 휴식 시간([`src/character/main.ts:118`](file:///C:/TEST/MikuChat-v3/src/character/main.ts#L118))**이 결합되어 발생한 지연임이 확인되었습니다.

#### 10개 문장 구간별 세분화 실측치 (ms)
| 문장 | 텍스트 | blob URL | new Audio | onloadedmetadata | play() 호출 | play() resolve | firstFrame (rAF) | visemeSet | 합계 (ms) |
|---|---|---|---|---|---|---|---|---|---|
| **1** | `안녕!` | 0.60 | 0.10 | 5.60 | 0.10 | 34.70 | 724.20 | 0.20 | 765.40 |
| **2** | `오늘 날씨가... 좋아.` | 1.30 | 0.00 | 2.50 | 0.00 | 5.00 | 826.50 | 0.20 | 835.50 |
| **3** | `창밖을 보니까... 있어!` | 0.80 | 0.00 | 2.50 | 0.00 | 5.00 | 178.30 | 0.00 | 186.60 |
| **4** | `너랑 이렇게... 것 같아.` | 0.40 | 0.00 | 2.30 | 0.00 | 5.40 | 797.80 | 0.00 | 805.90 |
| **5** | `혹시 오늘... 계획이 있어?` | 0.50 | 0.00 | 2.30 | 0.20 | 5.00 | 715.40 | 0.10 | 723.30 |
| **6** | `재미있는 계획이... 알려줘~` | 0.60 | 0.00 | 2.30 | 0.00 | 4.90 | 695.20 | 0.10 | 703.10 |
| **7** | `우리 같이... 부르자!` | 1.20 | 0.00 | 2.50 | 0.10 | 4.90 | 42.90 | 0.00 | 51.50 |
| **8** | `내가 항상... 잊지 마!` | 0.50 | 0.00 | 2.30 | 0.00 | 4.60 | 557.20 | 0.10 | 564.70 |
| **9** | `오늘도 활기차고... 바랄게~` | 0.50 | 0.10 | 2.60 | 0.10 | 5.40 | 756.30 | 0.00 | 764.90 |
| **10** | `언제든지... 불러줘!` | 1.20 | 0.10 | 3.30 | 0.00 | 5.90 | 351.10 | 0.00 | 361.60 |

#### 구간별 통계 (p50 / max)
* **Blob URL 생성**: p50 **0.60 ms** / max 1.30 ms
* **new Audio() 생성**: p50 **0.00 ms** / max 0.10 ms
* **onloadedmetadata 대기**: p50 **2.50 ms** / max 5.60 ms
* **play() 동기 호출**: p50 **0.10 ms** / max 0.20 ms
* **play() Promise Resolve**: p50 **5.00 ms** / max 34.70 ms
* **첫 프레임 렌더 (rAF)**: p50 **705.30 ms** / max 826.50 ms (비가시 창 rAF 스케줄링 간격)
* **첫 Viseme setValue**: p50 **0.10 ms** / max 0.20 ms

---

### 2. 실제 대화 5턴 문장별 전송·수신·재생 시각 및 무음 간극 실측
* 각 대화 턴은 LLM이 2개 이상의 문장으로 응답하도록 유도하여 문장 간 실제 무음 간극을 계측했습니다.

| 턴 | 문장 내용 | 문장 확정 (ms) | TTS 요청 (ms) | WAV 수신 (ms) | 합성 소요 (ms) | 재생 시작 (ms) | 재생 종료 (ms) | 문장 간 무음 간극 (ms) |
|---|---|---|---|---|---|---|---|---|
| **Turn 1 - S1** | `안녕 미쿠야!` | 23960.3 | 23960.3 | 24491.4 | 531.1 ms | 24495.1 | 25656.1 | - (첫 문장) |
| **Turn 1 - S2** | `오늘 날씨가 정말 화창해서 기분이 좋아.` | 25005.1 | 25005.1 | 26286.2 | 1281.1 ms | 26289.2 | 28289.2 | **633.1 ms** |
| **Turn 2 - S1** | `오늘 어떤 노래 들었어?` | 26795.5 | 26795.5 | 27911.3 | 1115.8 ms | 27914.4 | 29679.1 | - (첫 문장) |
| **Turn 2 - S2** | `너랑 같이 들으면 더 좋을 것 같아!` | 28420.7 | 28420.7 | 29633.4 | 1212.7 ms | 29636.8 | 31636.8 | **0.0 ms** (사전 다운로드 완료) |
| **Turn 3 - S1** | `오늘 재미있는 일 있었어?` | 30152.7 | 30152.7 | 31000.4 | 847.7 ms | 31003.6 | 32907.6 | - (첫 문장) |
| **Turn 3 - S2** | `나한테만 살짝 이야기해줘~` | 31514.4 | 31514.4 | 32593.4 | 1079.0 ms | 32597.2 | 34597.2 | **0.0 ms** (사전 다운로드 완료) |
| **Turn 4 - S1** | `피곤할 땐 따뜻한 차가 좋아.` | 33103.0 | 33103.0 | 33953.6 | 850.6 ms | 33956.8 | 35953.7 | - (첫 문장) |
| **Turn 4 - S2** | `푹 쉬고 좋은 꿈 꿔!` | 34465.0 | 34465.0 | 35437.0 | 972.0 ms | 35440.2 | 37440.2 | **0.0 ms** (사전 다운로드 완료) |
| **Turn 5 - S1** | `내일 또 만나서 이야기하자.` | 35942.3 | 35942.3 | 36926.0 | 983.7 ms | 36929.6 | 38929.6 | - (첫 문장) |
| **Turn 5 - S2** | `언제나 내가 곁에서 응원할게!` | 37430.3 | 37430.3 | 38362.0 | 931.7 ms | 38365.1 | 40365.1 | **0.0 ms** (사전 다운로드 완료) |

* **무음 구간 분석**:
  - Turn 1에서 S2의 TTS 합성(1,281ms)이 S1 재생 시간(1,161ms)보다 늦게 끝나 **633.1ms의 무음 간극**이 발생했습니다.
  - 반면 Turn 2~5에서는 S1 재생 시간 동안 S2의 합성이 백그라운드에서 미리 완료되어 **무음 간극이 0.0ms (큐에서 즉시 연결 재생)**로 매끄럽게 연결되었습니다.
  - 여기에 `character/main.ts:118`의 의도된 `setTimeout(..., 280)`이 더해져 실제 앱에서는 280ms의 호흡 공백이 발생합니다.

---

### 3. Fish Audio WebSocket 스트리밍 전환 예상 효과 및 기술 분석 (제안)

#### A. 첫 오디오 청크까지 예상 지연 (Time to First Audio Chunk)
* **현재 배치 방식**:
  문장 완성 대기(~350ms) + HTTP POST 전체 WAV 생성 및 다운로드(~582ms) + 오디오 준비(~5ms) = **약 930ms ~ 1,200ms**
* **WebSocket 스트리밍 도입 시**:
  - LLM 첫 토큰(TTFT ~27ms) 수신 즉시 WebSocket `textEvent`로 텍스트 전송.
  - Fish Audio 스트리밍 엔진이 첫 5~10글자 수신 즉시 첫 번째 PCM/Opus 청크 스트리밍 시작 (~100ms).
  - 네트워크 왕복 지연(~40ms) + 첫 청크 Web Audio 디코딩(~3ms) = **첫 소리 출력까지 약 170ms ~ 220ms**.
  - **예상 효과: 첫 발성 지연 700ms 이상 단축 (약 4배 이상 빠른 응답 체감)**.

#### B. 필요한 코드 변경 지점 (파일:줄번호)
1. [`electron/tts.ts:450-528`](file:///C:/TEST/MikuChat-v3/electron/tts.ts#L450-L528) (`FishAudioTts`):
   - 기존 `fetch("https://api.fish.audio/v1/tts")` HTTP POST 코드를 `wss://api.fish.audio/v1/tts/live` 웹소켓 연결 및 청크 핸들러로 교체.
2. [`electron/main.ts:510-523`](file:///C:/TEST/MikuChat-v3/electron/main.ts#L510-L523) (`completeLlmStream onDelta`):
   - 문장 종결 부호(`.!?`)까지 기다려 `extractConversationalChunks`를 거치는 구조를 우회하고, LLM 토큰이 들어오는 즉시 WebSocket에 `textEvent`로 파이프라이닝.
3. [`src/character/main.ts:96-130`](file:///C:/TEST/MikuChat-v3/src/character/main.ts#L96-L130) (`playSingleWav`):
   - `new Audio(blobUrl)` DOM 엘리먼트 재생 방식 제거.
   - Web Audio API의 `AudioContext` 기반 순환 버퍼(Streaming Audio Buffer Source) 또는 `MediaSource` 기반 PCM 실시간 스트리밍 재생 엔진으로 전면 개편.

#### C. 기술적 리스크 3개
1. **리스크 1: 네트워크 지터(Jitter)로 인한 버퍼 언더런(Under-run) 및 오디오 뚝뚝 끊김(Popping/Click)**
   - 인터넷 지연이 일시적으로 튀면 수신되는 오디오 청크가 재생 속도를 따라가지 못해 발화 도중 소리가 찢어지거나 뚝뚝 끊어지는 현상 발생. 50~100ms 수준의 지터 버퍼(프리롤 버퍼) 제어 로직이 필수적임.
2. **리스크 2: 립싱크(Lip-Sync) 동기화 복잡도 급증 (Phonetic Drift)**
   - 현재는 완성된 단일 WAV 파일의 전체 길이를 바탕으로 텍스트를 균등 분할해 입을 움직이지만, 스트리밍 상태에서는 전체 길이를 미리 알 수 없습니다. 따라서 오디오 실시간 PCM 진폭 분석(Web Audio `AnalyserNode`) 기반 립싱크로 전환하지 않으면 소리가 나기 전에 입이 먼저 닫히는 심각한 불일치가 발생합니다.
3. **리스크 3: 대화 중단(Barge-in / Interruption) 시 WebSocket 세션 제어 레이스 컨디션**
   - 미쿠가 말하는 도중 사용자가 말을 가로채거나 새 입력을 보낼 때(`Ipc.STOP_AUDIO`), 기존 WebSocket 스트림에 취소 이벤트를 전송하고 클라이언트 오디오 버퍼를 즉시 비우지 않으면, 이전 발화의 잔여 오디오 청크가 뒤늦게 재생되는 버퍼 오염 문제가 발생할 수 있습니다.
