export const Ipc = {
  READY: "ready",
  STATE_SYNC: "state-sync",
  SETTINGS_UPDATE: "settings-update",
  USER_SUBMIT: "user-submit",
  PTT_START: "ptt-start",
  PTT_STOP: "ptt-stop",
  SPEAKING: "speaking",
  TTS_AUDIO: "tts-audio",
  TTS_WEB: "tts-web",
  TTS_VISEME: "tts-viseme",
  TTS_STATUS: "tts-status",
  TTS_ERROR: "tts-error",
  TTS_TIMING: "tts-timing",
  EMOTION: "emotion",
  GESTURE: "gesture",
  SET_CLICK_THROUGH: "set-click-through",
  LLM_DELTA: "llm-delta",
  VOICES_LIST: "voices-list",
  PREVIEW_VOICE: "preview-voice",
  PLAY_PREVIEW_AUDIO: "play-preview-audio",
  ERROR: "error",
  CLEAR_HISTORY: "clear-history",
  CHAT_CLEARED: "chat-cleared",
  // V3 Additions:
  WINDOW_DRAG: "window-drag",
  SET_SCALE: "set-scale",
  PLAY_GESTURE: "play-gesture",
  STOP_AUDIO: "stop-audio",
  CAPTURE_SCREEN: "capture-screen",
  CAPTURE_MOUSE_REGION: "capture-mouse-region",
  OPEN_SETTINGS: "open-settings",
  CLOSE_SETTINGS: "close-settings",
  LOAD_VRM_MODEL: "load-vrm-model",
  SELECT_VRM_FILE: "select-vrm-file",
  LOAD_VRMA_MOTION: "load-vrma-motion",
  SELECT_VRMA_FILE: "select-vrma-file",
  PREVIEW_VRMA_MOTION: "preview-vrma-motion",
  VRMA_MOTIONS_LIST: "vrma-motions-list",
  SELECT_AUDIO_FILE: "select-audio-file",
  TEST_FISH_VOICE: "test-fish-voice",
  SEARCH_FISH_MODELS: "search-fish-models",
  CREATE_CUSTOM_VOICE: "create-custom-voice",
  VRM_MODELS_LIST: "vrm-models-list",
  // Language Tutor & SRS:
  ADD_SRS_CARD: "add-srs-card",
  GET_SRS_CARDS: "get-srs-cards",
  REVIEW_SRS_CARD: "review-srs-card",
  SRS_CARDS_DATA: "srs-cards-data",
  TOGGLE_CHAT_MODE: "toggle-chat-mode",
  SET_CHAT_MODE: "set-chat-mode",
  GET_OLLAMA_MODELS: "get-ollama-models",
  OLLAMA_MODELS_LIST: "ollama-models-list",
  SET_VIEW_MODE: "set-view-mode",
  TOGGLE_MUTE: "toggle-mute",
  TOGGLE_CHAT_WINDOW: "toggle-chat-window",
  QUIT_APP: "quit-app",
  OPEN_EXTERNAL_URL: "open-external-url",
  RECHECK_PROVIDER: "recheck-provider",
  DOWNLOAD_VOICE_SET: "download-voice-set",
  OPEN_DOWNLOADS_FOLDER: "open-downloads-folder",
} as const;

export type IpcChannel = (typeof Ipc)[keyof typeof Ipc];
